---
- name: Configure .bashrc
  hosts: all
  tags: always, bashrc
  tasks:
    - name: Link bashrc-snippets to home directory
      file:
        src: "{{ inventory_dir }}/bashrc.d"
        dest: "{{ ansible_env.HOME }}/.bashrc.d"
        state: link

    - name: Add load of bashrc snippets to .bashrc
      blockinfile:
        path: "{{ ansible_env.HOME }}/.bashrc"
        block: |
          # Load bashrc snippets
          for file in ~/.bashrc.d/enabled/*.bashrc; do
            source $file
          done

    - name: Enable default bashrc snippets
      file:
        src: "{{ inventory_dir }}/bashrc.d/{{ item }}"
        dest: "{{ inventory_dir }}/bashrc.d/enabled/{{ item }}"
        state: link
      with_items:
        - "000-setup-location.bashrc"
        - "002-prompt.bashrc"
        - "004-bash-history.bashrc"

    - name: Add .bash_aliases
      copy:
        src: "{{ inventory_dir }}/bash_aliases"
        dest: "{{ ansible_env.HOME }}/.bash_aliases"
        mode: 0644

    - name: Add .inputrc for history search using arrow keys
      copy:
        src: "{{ inventory_dir }}/inputrc"
        dest: "{{ ansible_env.HOME }}/.inputrc"
        mode: 0644
