---
- name: Common pre-requisites
  hosts: all
  tags: common
  tasks:
    - name: Create tarballs directory
      file:
        path: "{{ inventory_dir }}/tarballs"
        state: directory
        mode: 0755
