---
- name: Some extra stuff that is nice to have around
  hosts: all
  tags: extras
  vars:
    chrome_deb: "google-chrome-stable_current_amd64.deb"
  tasks:
    - name: Install other apt packages
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - curl
        - git
        - graphviz
        - jq
        - python3-pip
        - python3-venv
        - pavucontrol
        - meld
        - htop
        - dos2unix

    - name: Install apt packages not installable in Github Actions
      become: true
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      with_items:
        - docker.io
      when: ansible_env.IS_GITHUB_CI is not defined

    - name: Install git-toprepo
      ansible.builtin.pip:
        name: git-toprepo
        extra_args: --user

    - name: Download google-chrome-stable
      ansible.builtin.get_url:
        url: "https://dl.google.com/linux/direct/{{ chrome_deb }}"
        dest: "{{ inventory_dir }}/tarballs/{{ chrome_deb }}"
        mode: "0644"

    - name: Install google-chrome-stable
      become: true
      ansible.builtin.apt:
        deb: "{{ inventory_dir }}/tarballs/{{ chrome_deb }}"
        state: present

    - name: Install jfrog cli
      ansible.builtin.get_url:
        url: "https://releases.jfrog.io/artifactory/jfrog-cli/v2-jf/[RELEASE]/jfrog-cli-linux-amd64/jf"
        dest: "{{ ansible_env.HOME }}/.local/bin/jfrog"
        mode: "0755"
