---
- name: Setup Visual Studio Code
  hosts: all
  tags: vscode
  tasks:
    - name: Install VS Code with option --classic
      community.general.snap:
        name: code
        classic: true

    - name: Configure VS Code
      block:
        - name: Ensure VS Code settings directory exists
          file:
            path: "{{ ansible_env.HOME }}/.config/Code/User"
            state: directory

        - name: Read existing settings.json
          slurp:
            src: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"
          register: existing_settings

        - name: Read new settings from vscode_settings.json
          slurp:
            src: "{{ inventory_dir }}/vscode_settings.json"
          register: new_settings

        - name: Merge settings
          set_fact:
            merged_settings: "{{ (existing_settings.content | b64decode | from_json) | combine(new_settings.content | b64decode | from_json) }}"

        - name: Write merged settings to settings.json
          copy:
            content: "{{ merged_settings | to_nice_json }}"
            dest: "{{ ansible_env.HOME }}/.config/Code/User/settings.json"
            backup: yes
